### ISSUE TITLE
Compile to JavaScript

### ISSUE THREAD

**Issue by jamesaoverton** [knotation/knotation-cljc#2]
The current code only works for Clojure, mostly because of `throw`, but it should compile to ClojureScript.

**Comment by inaimathi** [comment]
As of https://github.com/knotation/knotation-cljc/commit/281ed82d70c2c8fe43b16f551c46731535001167, this compiles with `lein cljsbuild once`. There are still some unnamed variable warnings; I'll want to test it out before we call this done.
