### ISSUE TITLE
How to handle exceptions?

### ISSUE THREAD

**Issue by jamesaoverton** [knotation/knotation-cljc#3]
The current code has very little/poor exception handling. We can just throw exceptions (making sure it works for JVM and JavaScript) but there's probably a better way. Use cases:

- reporting errors when called as a library or from the command-line
- reporting errors in CodeMirror (interactive editing)
- warning about missing labels, and maybe calling an API to find good labels, or generating a new subject with that label, or just reporting

**Comment by inaimathi** [comment]
Thought about it a bit, and did some reading. I propose that https://github.com/knotation/knotation-cljc/pull/4 would give us what we want in most use cases (we'd still need to do weird things to declare new exception types that are clj/cljs cross-compatible https://stackoverflow.com/questions/3835331/custom-exceptions-in-clojure, but this at least handles the dispatch end of the equation).
