### ISSUE TITLE
Rework Turtle rendering

### ISSUE THREAD

**Issue by jamesaoverton** [knotation/knotation-cljc#7]
`ttl.cljc` on the current `revision` branch includes a `merge-stanzas` function that I'm worried about. It tries to zip the input triples and output strings together, but looks too fragile to me. I think it would be better to do a deep refactor, so that `render-subject` and `render-declaration` return a triple map with the output string `assoc`ed in.

**Comment by inaimathi** [comment]
Agreed. Because of the way the `kn->ttl` transformation works, it looks like line numbering is going to be tied pretty deeply to the internals of the rendering step. This is going to be a bigger fix though; I'll try to get to it tomorrow or over the weekend.

**Comment by inaimathi** [comment]
Got a start on this as of https://github.com/knotation/knotation-cljc/commit/0e62fae106b4f795485428064065f8df52077ce8

I've still got to make stanza assignment more granular, make sure that blank lines are inserted at the end of each stanza, and make sure that the `clj-api/render-string` hook works properly (this is the thing that gets called from the Knode endpoint. It should probably call `api/render-to` internally).

**Comment by inaimathi** [comment]
Blank lines and the `api/render-to` issue fixed as of https://github.com/knotation/knotation-cljc/commit/9a6440fa18a82692d0c1179a2b6cb8c1cb3e734d

Still need to make stanza rendering more granular across states rather than clustering to first incoming state.

**Comment by inaimathi** [comment]
More work in the `revision` branch. Minor refactorings all-round, and I added the tests for `annotation`s. I need to take a break from this one; it's beginning to feel like hitting my head against the wall. Moving on to the other tickets for the moment.

**Comment by jamesaoverton** [comment]
Closed by 766b2b8d3a9dea6323a499233298391cffaacf4a
